### ISSUE TITLE
Support Emoji 11

### ISSUE THREAD

**Issue by rijn** [sskhandek/react-native-emoji-input#24]
Related iamcal/emoji-data#145 iamcal/emoji-data#146

**Comment by mark-wade** [comment]
Hey @rijn - just out of interest - is this something you do manually, or do you have some kind of tools to automate this?

I only need the final emoji.json file (not the sprite sheets) and may end up just adding the new ones manually but if there's a straightforward way to do it "properly" that you can explain, I'd love to be able to submit a PR.

**Comment by rijn** [comment]
@mark-wade I would not do it manually. The [emoji-data](https://github.com/iamcal/emoji-data) repo has a script to compile unicode standard. I'm using that with manually added shortnames. It works just fine.
