### ISSUE TITLE
Option to prevent keyboard from getting dismissed when emoji is pressed. 

### ISSUE THREAD

**Issue by salhotra** [sskhandek/react-native-emoji-input#45]
**Use case:**
When an emoji is pressed, it does not register the touch event when the keyboard is visible. This is a very common scenario as input box will generally be focused when the user taps on emojis.

**Solution**
I'm creating a PR with `keyboardShouldPersistTaps` prop. This works on RecyclerListView exactly as it works on Scrollview.

**Comment by rijn** [comment]
Great! Thanks for the PR. Accepted.
